[package]
name = "ash_term"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
libc = "0.2.150"
log = { workspace = true }
crossbeam-channel = "0.5.8"
num-traits = "0.2.17"
unicode-width = "0.1.11"
unicode-segmentation = "1.10.1"
compact_str = "0.7.1"

[lints]
workspace = true
