[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
fern = "0.6.2"
log = "0.4.20"
divan = "0.1.2"
serde = { version = "1.0.193" }
serde_json = "1.0.108"
thiserror = "1.0.50"

[workspace.lints.clippy]
correctness = "deny"
todo = "warn"
