[package]
name = "ash_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
ash_gap_buffer = { path = "../ash_gap_buffer" }
ash_term = { path = "../ash_term" }
chrono = "0.4.31"
fern = "0.6.2"
log = { workspace = true }

[lints]
workspace = true
