[package]
name = "ash_common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
fern = { workspace = true }
log = { workspace = true }
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.50"

[lints]
workspace = true
